### ISSUE TITLE
dropping fields I asked it to keep

### ISSUE THREAD

**Issue by dmd** [KitwareMedical/dicom-anonymizer#10]
dicom-anonymizer seems to be deleting some dicom fields, even if asked to keep them:

```
$ dcmdump input.dcm | grep 0029,0010
(0029,0010) LO [SIEMENS CSA HEADER]                     #  18, 1 PrivateCreator

$ dicom-anonymizer input.dcm output.dcm -t '(0x0029,0x1010)' keep
100%|███████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.67it/s]

$ dcmdump output.dcm | grep 0029,0010

$
```

**Comment by laurennlam** [comment]
It's possible that this tag is a private tag. Private tags are always deleted for anonymization.
cf line 247 of simpledicomanonymizer.py

**Comment by dmd** [comment]
Yes, it is. That's annoying, as it [breaks conversion to Nifti later](https://github.com/rordenlab/dcm2niix/issues/275)

**Comment by laurennlam** [comment]
Hi @dmd, Sorry for the late answer. So, after checking, it seems that all private tags are mandatory removed.
We can pass through that but, I want to warn you about possible changing:
- Private tags have a "Private creator" such as (0029, 0020). These private tags are heads of blocks that contain sub private tags (0029, 1008), (0029, 1009),...).
- if you want to keep a private creator, then all subtags will be removed and you'll have to manually define which one you want to keep/modify
- if you manually define that you want to only keep a sub element, then you will have a Private Creator then. Sub private element of a block cannot "lives" without a creator.
Does this sound good to you ?

**Comment by dmd** [comment]
Yes, that's reasonable!

**Comment by laurennlam** [comment]
#11
