### ISSUE TITLE
Change only 1 DICOM tag

### ISSUE THREAD

**Issue by finetjul** [KitwareMedical/dicom-anonymizer#3]
How can I  change only 1 DICOM tag from the command line ?

If I do:
 dicom-anonymizer InputPath OutputPath --dictionary pathToMyDict.json

then all the tags are anonymized in addition to the tags I list in my dictionary.

**Comment by laurennlam** [comment]
The goal of the dictionary is not to only anonymize some tags but to change the anonymize action to specific tags.
If you want to keep all tags and only change some, then take à look here : https://github.com/KitwareMedical/dicom-anonymizer#customoverrides-actions
