### ISSUE TITLE
Change 1 DICOM tag

### ISSUE THREAD

**Issue by finetjul** [KitwareMedical/dicom-anonymizer#4]
How can I set one tag to a specific value (no regexp) from the command line?

e.g. 
```
dicom-anonymizer InputPath  OutputPath -t (0x0010,0x0010) DOE^JOHN
```

**Comment by laurennlam** [comment]
From the command line, with the current implementation, you can't. You'll have to refer to https://github.com/KitwareMedical/dicom-anonymizer#customoverrides-actions
