### ISSUE TITLE
Add conda package

### ISSUE THREAD

**Issue by sarthakpati** [KitwareMedical/dicom-anonymizer#40]
Hi,

It would be great if you could also add a conda package in addition to the pip. It would make constructing complex dependencies (especially those relying on c++ libraries) much easier.

I am happy to work on it if you want. If you could publish the sdist of this package in pip, I can take care of the rest. 

Cheers,
Sarthak

**Comment by finetjul** [comment]
Hi Sarthak,

Yes, we have recently started working on it. It will be done in the next coming days !

Thanks for your patience.

Julien

**Comment by pchoisel** [comment]
Hi @sarthakpati,
Sorry for the time it took, the sdist has been published. Could you try to create a conda package ?
Have a great day,
