### ISSUE TITLE
Patient data within DirectoryRecordSequence (of DICOMDIR file) not anonymized

### ISSUE THREAD

**Issue by samueljohn** [KitwareMedical/dicom-anonymizer#41]
Dear KitwareMemdical,

I have a DICOMDIR that still contains the PatientName after running it through the default anonymizer!

Using the version from 1690b78 (installed via pip install git+https...) and pydicom version  2.3.1, I noticed that I have encountered a DICOMDIR file that contains a DirectoryRecordSequence with patient data and it looks like:

```
Dataset.file_meta -------------------------------
(0002, 0000) File Meta Information Group Length  UL: 180
(0002, 0001) File Meta Information Version       OB: b'\x00\x01'
(0002, 0002) Media Storage SOP Class UID         UI: Media Storage Directory Storage
(0002, 0003) Media Storage SOP Instance UID      UI: 2.25.297764926861898021974262533209051862847
(0002, 0010) Transfer Syntax UID                 UI: Explicit VR Little Endian
(0002, 0012) Implementation Class UID            UI: 1.2.276.0.45.1.1.0.71.20130122
(0002, 0013) Implementation Version Name         SH: 'DicomWeb_71'
-------------------------------------------------
(0004, 1130) File-set ID                         CS: 'VISAGECS_MEDIA'
(0004, 1200) Offset of the First Directory Recor UL: 406
(0004, 1202) Offset of the Last Directory Record UL: 406
(0004, 1212) File-set Consistency Flag           US: 0
(0004, 1220)  Directory Record Sequence  1 item(s) ---- 
   (0004, 1400) Offset of the Next Directory Record UL: 0
   (0004, 1410) Record In-use Flag                  US: 65535
   (0004, 1420) Offset of Referenced Lower-Level Di UL: 0
   (0004, 1430) Directory Record Type               CS: 'PATIENT'
   (0008, 0005) Specific Character Set              CS: 'ISO_IR 100'
   (0010, 0010) Patient's Name                      PN: 'NOT^ANONYM'
   (0010, 0020) Patient ID                          LO: '12345678'
   (0010, 0030) Patient's Birth Date                DA: '19000101'
   ------—-
```

Note, I manually changed the patient data in order not to disclose anything here. The DirectoryRecordSequence had over 700 entries, so for debugging, I removed all but one entry to minimally demo the issue.

I ran `dicomanonymizer.anonymize_dicom_file('DICOMDIR', 'DICOMDIR-anon')` and expected the patient name etc. to be removed or replaced.

Instead, when I then `pydicom.read_file('/DICOMDIR-anon')` I got:

```
Dataset.file_meta -------------------------------
(0002, 0000) File Meta Information Group Length  UL: 180
(0002, 0001) File Meta Information Version       OB: b'\x00\x01'
(0002, 0002) Media Storage SOP Class UID         UI: Media Storage Directory Storage
(0002, 0003) Media Storage SOP Instance UID      UI: 2.25.172643117625232586517094341815358543841
(0002, 0010) Transfer Syntax UID                 UI: Explicit VR Little Endian
(0002, 0012) Implementation Class UID            UI: 1.2.276.0.45.1.1.0.71.20130122
(0002, 0013) Implementation Version Name         SH: 'DicomWeb_71'
-------------------------------------------------
(0004, 1130) File-set ID                         CS: 'VISAGECS_MEDIA'
(0004, 1200) Offset of the First Directory Recor UL: 406
(0004, 1202) Offset of the Last Directory Record UL: 406
(0004, 1212) File-set Consistency Flag           US: 0
(0004, 1220)  Directory Record Sequence  1 item(s) ---- 
   (0004, 1400) Offset of the Next Directory Record UL: 0
   (0004, 1410) Record In-use Flag                  US: 65535
   (0004, 1420) Offset of Referenced Lower-Level Di UL: 0
   (0004, 1430) Directory Record Type               CS: 'PATIENT'
   (0008, 0005) Specific Character Set              CS: 'ISO_IR 100'
   (0010, 0010) Patient's Name                      PN: 'NOT^ANONYM'
   (0010, 0020) Patient ID                          LO: '12345678'
   (0010, 0030) Patient's Birth Date                DA: '19000101'
   ---------
```

The Instance UID changed, but not the Patient data within the sequence (of len 1 here). I am not allowed to provide the full original file but I think this smaller one reproduces the issue.

- [DICOMDIR.zip](https://github.com/KitwareMedical/dicom-anonymizer/files/11111752/DICOMDIR.zip)
- [DICOMDIR-anon.zip](https://github.com/KitwareMedical/dicom-anonymizer/files/11111758/DICOMDIR-anon.zip)

Please feel free to include this file in your test suite.
Let me know if I can be helpful here.

Any quick fix idea would be welcome.

thanks, 
 Samuel

**Comment by pchoisel** [comment]
Hi @samueljohn,

This issue you are facing is expected. dicom-anonymizer only anonymizes a pre-defined set of tags that you can find in this file: https://github.com/KitwareMedical/dicom-anonymizer/blob/master/dicomanonymizer/dicomfields.py

The tag `(0x0004, 0x1220)  Directory Record Sequence` is not one of them. We'll talk internally about whether we should add this tag to the list.

In the meantime, you can add the parameter `-t '(0x0004, 0x1220)' replace` to your command line when calling dicom-anonymizer. It should add the missing tag to the list of tags to anonymize.

I hope this helps and I wish you a great day,
Paul

**Comment by samueljohn** [comment]
Dear @pchoisel, thank for your helpful explanation and suggestion!

At least to me, this came as a surprise and the Directory Record Sequence seems to be just a "list" that can contain some of the usual other dicom tags that should perhaps be traversed? But that would mean to handle this and potentially other sequence tags that act like they are building a hierarchical structure in the dicom.

If I hadn't manually inspected the DICOMDIR, I would have missed that - and it seems not to be uncommon to have patient data also in this sequence. At least this issue may warn others about this potential issue.

Thank you again, I ended up deleting the DICOMDIR and generating it a new from the FileSet of anonymized dicom files.

**Comment by pchoisel** [comment]
Hi @samueljohn,

After investigation and discussion with my colleagues, it appears that you should not try to anonymize a DICOMDIR file, you should rather re-generate it after the DICOM files have been anonymized.

I will still add instructions in the README file to let people know how to anonymize DICOMDIRs

**Comment by samueljohn** [comment]
Dear @pchoisel, that is exactly what I ended up doing.

Perhaps print a warning if the filename is "dicomdir", because I guess this could otherwise lead to potential leaking of patient information.
