### ISSUE TITLE
Example code encourages incorrect anonymization

### ISSUE THREAD

**Issue by smjoshiatglobus** [KitwareMedical/dicom-anonymizer#67]
The following code in `examples/anonymize_extra_rules.py` encourages incorrect anonymization by not removing series description. That tag should be removed! We should create the example using a different tag:
```
    def setup_series_description(dataset, tag):
        element = dataset.get(tag)
        if element is not None:
            element.value = f'{element.value}-{args.suffix}'
```

**Comment by smjoshiatglobus** [comment]
How about using (0x0010, 0x0010) - Patient Name, as an example extra rules. That tag is Z tag, so does not need to be deleted. Instead of using the default 'ANONYMIZED', the example can set `element.value` to `ANON^PATIENT`.

**Comment by pchoisel** [comment]
What we like in this example is that the function assigned to the series description tag reuses the value of the tag and just modifies it.  
What do you think about changing this function to something that takes the Patient Birth Date and sets its day to the first of the month ?

**Comment by smjoshiatglobus** [comment]
Agreed. Opened PR #72 for the fix.
