### ISSUE TITLE
add --version

### ISSUE THREAD

**Issue by dmd** [KitwareMedical/dicom-anonymizer#69]
A `--version` flag would be useful.

**Comment by pchoisel** [comment]
We already have one:
![image](https://github.com/KitwareMedical/dicom-anonymizer/assets/60932251/14266cea-0f06-4cb2-a7b1-600d158fe599)
Were you thinking about something else ?

**Comment by dmd** [comment]
Heh - that's new in 1.0.12, which, well, see #68  :)
