### ISSUE TITLE
AttributeError: 'int' object has no attribute 'elements'

### ISSUE THREAD

**Issue by dmd** [KitwareMedical/dicom-anonymizer#7]
This is super odd.

When I anonymize a SRe file (`SRe.1.3.12.2.1107.5.2.43.66094.30000020021213353802600000201`), I get:

```
Traceback (most recent call last):
  File "/home/ddrucker/venvs/test/bin/dicom-anonymizer", line 10, in <module>
    sys.exit(main())
  File "/home/ddrucker/venvs/test/lib/python3.7/site-packages/dicomanonymizer/anonymizer.py", line 144, in main
    anonymize(InputPath, OutputPath, newAnonymizationActions)
  File "/home/ddrucker/venvs/test/lib/python3.7/site-packages/dicomanonymizer/anonymizer.py", line 41, in anonymize
    anonymizeDICOMFile(inputFilesList[cpt], outputFilesList[cpt], anonymizationActions)
  File "/home/ddrucker/venvs/test/lib/python3.7/site-packages/dicomanonymizer/simpledicomanonymizer.py", line 241, in anonymizeDICOMFile
    anonymizeDataset(dataset, extraAnonymizationRules)
  File "/home/ddrucker/venvs/test/lib/python3.7/site-packages/dicomanonymizer/simpledicomanonymizer.py", line 253, in anonymizeDataset
    action(dataset, tag)
  File "/home/ddrucker/venvs/test/lib/python3.7/site-packages/dicomanonymizer/simpledicomanonymizer.py", line 126, in delete
    deleteElement(dataset, element)  # element.tag is not the same type as tag.
  File "/home/ddrucker/venvs/test/lib/python3.7/site-packages/dicomanonymizer/simpledicomanonymizer.py", line 110, in deleteElement
    deleteElement(subDataset, subElement)
  File "/home/ddrucker/venvs/test/lib/python3.7/site-packages/dicomanonymizer/simpledicomanonymizer.py", line 109, in deleteElement
    for subElement in subDataset.elements():
AttributeError: 'int' object has no attribute 'elements'
```

Now, here's the odd part.

Here's the code where it dies:

```
  def deleteElement(dataset, element):
      if element.VR == 'DA':
          replaceElementDate(element)
      elif element.VR == 'SQ':
          for subDataset in element.value:
              for subElement in subDataset.elements():         ### dying here
                  deleteElement(subDataset, subElement)
      else:
          del dataset[element.tag]
```

So I added a print statement:

```
  def deleteElement(dataset, element):
      if element.VR == 'DA':
          replaceElementDate(element)
      elif element.VR == 'SQ':
          for subDataset in element.value:
              print(element.value)             ### add this line
              for subElement in subDataset.elements(): 
                  deleteElement(subDataset, subElement)
      else:
          del dataset[element.tag]
```

**And now it doesn't fail - it works fine.**

My best guess is that printing element.value forces an enumeration which actually *changes* it - like maybe something without a value is forced to have an empty one instead?

**Comment by laurennlam** [comment]
what's the difference between Sre file and basic dicom file ?

**Comment by dmd** [comment]
I don't really know - it's a [Structured Reporting](http://dicom.nema.org/dicom/2013/output/chtml/part20/sect_A.3.html) file. 

Here is an example file that fails (zipped so I can upload to Github).

[SRe.1.3.12.2.1107.5.2.43.66094.30000020021213353802600000201.zip](https://github.com/KitwareMedical/dicom-anonymizer/files/5597797/SRe.1.3.12.2.1107.5.2.43.66094.30000020021213353802600000201.zip)

**Comment by dmd** [comment]
So, looks like those files are the Phoenix ZIP Acquisition Reports, which are images of documents which, themselves, contain PII. 

So I'm not sure what the right thing to do here is -- those files *can't* really be anonymized, they are intrinsically PII. But, on the other hand, *dicom-anonymizer* shouldn't crash on them, either!

**Comment by dmd** [comment]
If you'd like me to send you the file so you can test against it, let me know an email to send it to.

**Comment by finetjul** [comment]
What I do not understand is why `deleteElement` does not delete DA (date) elements.
Additionally, it does not delete sequences but their contents only.

I wonder if it should simply delete the element.
Finally, I wonder if browsing on a list can help. e.g.
```
for subDataset in list(element.value):
              for subElement in subDataset.elements():
                  deleteElement(subDataset, subElement)
```

**Comment by dmd** [comment]
@laurennlam Would you like me to send you a sample file that makes dicom-anonymizer crash?

**Comment by laurennlam** [comment]
Hi @dmd, for sure, you can send me the sample so that I can't check what's happening and trying to fix this.

**Comment by dmd** [comment]
Sent!

**Comment by laurennlam** [comment]
Thanks!

**Comment by laurennlam** [comment]
I investigated on what is happening with this file.
I pointed out several weird things.
- When I read the dicom file with slicer and check the metadata, everything seems clear. The tag (0040, a730) contains several sub sequences
- When we read the data with pydicom, the subsequences are not recognized as Sequence but as Dataset. I don't know why.

But, @finetjul suggested me to directly delete the tag without go through subsequences and it works well.
I'll make an update of the package.
Thanks for the report @dmd .

**Comment by laurennlam** [comment]
Hi @dmd,
Very sorry for the delay. I finally found out where the problem came from !
 According to the [documentation of the Value Representation](http://dicom.nema.org/dicom/2013/output/chtml/part05/sect_7.5.html), a sequence (VR = SQ) can be a sequence (list of sub elements) but it can also be a sequence of zeros (from which we cannot iterate). That's why the display error was :

> AttributeError: 'int' object has no attribute 'elements'

But I don't understand why it didn't fail when you used print...

With the fix I'll push, the dicom anonymization works without any error on the file you shared !

**Comment by dmd** [comment]
Thank you!
