### ISSUE TITLE
Proposal: Introduce ruff for code formatting and linting

### ISSUE THREAD

**Issue by smasuda** [KitwareMedical/dicom-anonymizer#75]
Hi!

I have started looking into the codes and have sent one PR, and noticed the current code base might be under some code formatter/linter other than ruff or black which are common these days.

How about introduce one of them like pydicom and make it as this project's default?
Even today some contributors have changed single quote to double qoute to surround string, which isn't consistent.

**Comment by pchoisel** [comment]
Fixed with #84
